services:
  postgres:
    container_name: postgres
    image: postgres:alpine3.18
    restart: always
    shm_size: 128mb
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - internal
networks:
  internal:
    driver: bridge
